name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    #     services:
    #       mysql:
    #         image: mysql:8.0.28
    #         env:
    #           MYSQL_USER: 127.0.0.1
    #           MYSQL_PASSWORD: test
    #           MYSQL_ROOT_PASSWORD: test
    #           MYSQL_DATABASE: test
    #         ports:
    #           - 3307
    #         options: >-
    #           --health-cmd="mysqladmin ping"
    #           --health-interval=10s
    #           --health-timeout=5s
    #           --health-retries=3

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      #       - uses: actions/checkout@v3
      #       - name: Build the Docker image
      #         run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      #       - name: verify MySQL connection from host
      #         run: |
      #           mysql --version
      #           sudo apt-get install -y mysql-client
      #           sudo service mysql start
      #           mysql -uroot -proot -e "CREATE DATABASE test"
      #           mysql -uroot -proot -e "SHOW DATABASES"

      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: create .env
        run: |
          touch .env.test
          echo DB_HOST=localhost >> .env.test
          echo DB_USERNAME=test >> .env.test
          echo DB_PASSWORD=test >> .env.test
          echo DB_DATABASE=test >> .env.test
          cat .env.test

      - name: install dependency
        if: steps.cache.output.cache-hit != true
        run: npm install --legacy-peer-deps

      - run: npm run db:up --env=test

      - run: npm ci
      - run: npm test
#         env:
#           CI: true
#           MYSQL_DATABASE: payhere
#           DB_USERNAME: root
#           DB_PASSWORD: root
#           DB_PORT: 3307
